postgresql:
  enabled: false

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

env:
  DB_HOSTNAME: "immich-postgres-rw.immich.svc.cluster.local"
  DB_USERNAME: "immich"
  DB_DATABASE_NAME: "immich"
  DB_PASSWORD: "strongPassword"

immich:
  persistence:
    enabled: true
    library:
      existingClaim: immich-library-pvc

  ingress:
    enabled: false

  database:
    host: immich-postgres-rw.immich.svc.cluster.local
    port: 5432
    username: immich
    password: strongPassword
    databaseName: immich

