# k8s/nextcloud/nextcloud-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/nextcloud/data