apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-nextcloud-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  volumeName: postgres-nextcloud-pv

