apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nextcloud-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/nextcloud/postgres
