# k8s/nextcloud/immich-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/immich/data