apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-cache-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: ml-cache-pv
