apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-immich-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/immich/postgres
