apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres
spec:
  capacity:
    storage: 10Gi                       # Adjust size as needed for the database
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Retain data if the claim is deleted
  storageClassName: ""                  # No storage class (binding by explicit volumeName)
  hostPath:
    path: /mnt/immich/postgres          # Host path for Postgres data
    type: DirectoryOrCreate
