apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-uploads-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/data/immich/uploads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-uploads
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: immich-uploads-pv
  storageClassName: ""
